
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: "10 Parker Street"
  # Location required to calculate the time the sun rises and sets
  latitude: 42
  longitude: -71
  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
      - 192.168.4.0/22

  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate

hacs:
  token: !secret gh_token

vesync:
  username: !secret vesync_user
  password: !secret vesync_pass

frontend: !include frontend.yaml

lovelace:
  mode: yaml
  #resources:
  #- url: /hacsfiles/kiosk-mode/kiosk-mode.js
  #  type: module

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml

input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
#devices: !include devices.yaml
